#!/usr/bin/env bash
# Cross-compile the kernels for a Cortex-M4 and build the unicorn host.
#   needs arm-none-eabi-g++ and unicorn (dnf: arm-none-eabi-gcc-cs-c++ unicorn-devel;
#   apt: gcc-arm-none-eabi libunicorn-dev)
set -euo pipefail
cd "$(dirname "$0")"
OUT=${OUT:-build}
mkdir -p "$OUT"
ARMFLAGS="-mcpu=cortex-m4 -mthumb -O2 -ffreestanding -fno-exceptions -fno-rtti -fno-threadsafe-statics -nostdlib -nostartfiles"
arm-none-eabi-g++ $ARMFLAGS -T link.ld kernels.cpp -o "$OUT/kernels.elf" -Wl,--gc-sections -Wl,-e,tvla_halt
arm-none-eabi-objcopy -O binary "$OUT/kernels.elf" "$OUT/kernels.bin"
{
  echo "/* generated by build.sh from kernels.elf */"
  arm-none-eabi-nm "$OUT/kernels.elf" | awk '$3 ~ /^tvla_/ { printf "#define %s 0x%sull\n", toupper($3), $1 }'
} > "$OUT/symbols.h"
${CXX:-g++} -std=gnu++17 -O2 -Wall tvla.cpp -o "$OUT/tvla" -lunicorn
echo "built $OUT/tvla ($(wc -c < "$OUT/kernels.bin") bytes of Cortex-M4 code)"
