#!/usr/bin/env bash
# Cross-compile the kernels for a Cortex-M4 and build the unicorn host.
#   needs arm-none-eabi-g++, unicorn and capstone (dnf: arm-none-eabi-gcc-cs-c++ unicorn-devel
#   capstone-devel; apt: gcc-arm-none-eabi libunicorn-dev libcapstone-dev). A capstone built
#   elsewhere: CAPSTONE_PREFIX=/path ./build.sh
set -euo pipefail
cd "$(dirname "$0")"
OUT=${OUT:-build}
mkdir -p "$OUT"
ARMFLAGS="-mcpu=cortex-m4 -mthumb -O2 -ffreestanding -fno-exceptions -fno-rtti -fno-threadsafe-statics -nostdlib -nostartfiles"
arm-none-eabi-g++ $ARMFLAGS -T link.ld kernels.cpp -o "$OUT/kernels.elf" -Wl,--gc-sections -Wl,-e,tvla_halt
arm-none-eabi-objcopy -O binary "$OUT/kernels.elf" "$OUT/kernels.bin"
{
  echo "/* generated by build.sh from kernels.elf */"
  arm-none-eabi-nm "$OUT/kernels.elf" | awk '$3 ~ /^tvla_/ { printf "#define %s 0x%sull\n", toupper($3), $1 }'
} > "$OUT/symbols.h"
CS_CFLAGS=""; CS_LIBS="-lcapstone"
if [ -n "${CAPSTONE_PREFIX:-}" ]; then
  CS_CFLAGS="-I$CAPSTONE_PREFIX/include"
  CS_LIBS="$(ls "$CAPSTONE_PREFIX"/lib*/libcapstone.a 2>/dev/null | head -1)"
  [ -n "$CS_LIBS" ] || CS_LIBS="-L$CAPSTONE_PREFIX/lib -lcapstone"
fi
${CXX:-g++} -std=gnu++17 -O2 -Wall $CS_CFLAGS tvla.cpp -o "$OUT/tvla" -lunicorn $CS_LIBS
echo "built $OUT/tvla ($(wc -c < "$OUT/kernels.bin") bytes of Cortex-M4 code)"
