# XMSS byte-compatibility with the RFC 8391 reference implementation.
#
# This is the check the package previously could not make. The
# documentation used to say the scheme "follows the RFC 8391
# construction but is not claimed to be byte-compatible with other
# implementations" -- and that was true, because three things diverged
# from the specification:
#
#   1. The WOTS+ chain seeds came from PRF(SK_SEED, toByte(i, 32))
#      rather than PRF_keygen(SK_SEED, PUB_SEED || ADRS). A sound
#      pseudorandom function, and not the specified one.
#   2. The message digest was keyed with PUB_SEED, with the index and
#      root pushed into the message, rather than keyed with
#      R || root || toByte(idx, n) as RFC 8391 section 4.1.9 requires.
#   3. There was no SK_PRF at all, so the per-signature randomiser R
#      the RFC binds the digest to did not exist.
#
# All three are fixed, and the whole 2500-byte signature now matches the
# reference implementation byte for byte. The vectors below are embedded
# rather than generated, so this check needs no network and no C
# toolchain -- and so that a future change to the construction fails
# here rather than silently producing signatures nobody else can read.

test_that("the signature is byte-identical to the RFC 8391 reference", {
  # XMSS-SHA2_10_256, seed[i] = i for 3n bytes, index 0, message
  # 01 02 03. Generated by the XMSS reference implementation
  # (github.com/XMSS/xmss-reference, commit fetched 2026-09-12) and
  # embedded so the check needs no network and no C toolchain.
  ref_sig <- paste0(
    "0000000011c3e8f92a6565812dad1b5e748d117a17f1f9f07336cf6c1eaa",
    "3a2b77071cb2d756a134332eac734f05971809226c74218f2c652553c2d3",
    "403f448fe8e224421d1c2168ecd5da3f7279810a752b5e675027260a0771",
    "cb561acfc269a71b51e55e421c313f3bd3e80f10cdfdd629adeada5485b8",
    "6015a5bfc825a061efa90cdc49ccede94eacd7dbb05ae1a0acbdbc467d4f",
    "351e8b2ffe66fa94019a459e22c6643e6075bb8527fa21801fac6323f0e6",
    "98a6253009bfc3e8b59d12c22ef9395b0e1dc288b34e296ce86a59c54a05",
    "c60361af9873bd2cf58d477769eb716755a998fa0f67819f66ac70da33de",
    "47ba9f2d025cbbbff06572cb0ee5041c5ff92f773ca6b7fe472b030d17c6",
    "7236122fbba0f69a82d012de3bd81bf477d21b9c268b6d7d51aadd4f4508",
    "0ae482fcd833105f97ef3f84dbcd6fc69341f160906aeb388cdd48d27c06",
    "21997c18f6f227463886363e71976d255ae4bde2654e2c3fb4f8fcc7cb1e",
    "00d539718890af2614487f2920a9108214dd60ec111bdf2e0470db2deac9",
    "77489e79a9e47e2447b8f23b72b02b47e1201bc2d755cf5799f3559e1e3c",
    "3588de92a77e4f729de899014ffdef72ac8e0b5069beb527aff97f8e9f79",
    "6fd8966b286e5552ea201e60eae38e76f39e67452f4028e988ca23aab646",
    "a1f15f544ca88e67ffa908bb71021e144ac910abcc666a2b2a8cad7a3f8b",
    "feae5283d50c9db81a7f298f18fe3012a340993822c6b1f409ec89dc00df",
    "16c9b5a3af215acdcb08bcf82f9b264bd5385fee409dd883088114ad0354",
    "36b20ee442225619a1de35112daaea45cd5ea164278ea87a7c4ee4e577d7",
    "df7630479ebb34d725de75578fa5165a1057310d736aa2cccd339f7c7405",
    "1265a747f94a50488083a165af4ace33ac375c9c1462b9834b9179108560",
    "a8c47b783ecc13362f021ec2d618893712a3cf866ed04685db1f2057c4da",
    "9c72e94459268eb052a56f3dbef00353373f642c413d54febeb0786c7de4",
    "691e558bc20d9e7115c129327920f0b7a0ce89f3f4856cb4ecc2acc296a9",
    "8be4786753fe3a65425bcf945aaad312ba8eed4a2590364df159d7673e13",
    "bd09de7029a8540f842928f24fba698f57d97a608d1c1a0fd1931c87d622",
    "1d5c50da8c06bd6dc7c5129557984b5357771eaceb1553a4c690f4ef7f0d",
    "7dd917e2475e7997315731c4efaff274ec318c189a393ab27ae500bea019",
    "0a136da835097aae677ed07273ae857f1e3f97f4c08a9a1c64f8ac89117b",
    "1ff43d5a3ed9b3cf8afba732a4e7f4bcb56589c7c0ed6515cd45c7b91114",
    "e9ef494dae610e227324706588b06bdb027d1497abe40c633fcb5e4f6aff",
    "e81ccb942e4400c55a0eabb60e7d814596bb95a7ad486c54e6021cd4a1b1",
    "8895a4378e5589910b8dc13d824cd8b55c601b736af6d5c3539407eb5f59",
    "be2f47479139dbccce9d091341e69bac1ad5a6a2c2a2f68dc61e9fab0a3b",
    "d42afceeb550b6910e767d9f9b8464eabd5be29db2d5e989111d06417825",
    "5b1216b4406c62b253ae77b4583db1d4e330a8857dbea3be6869f31bee5f",
    "08ac15e17af8592b54813f8981dd8f115733f6ff4b089a80b36da9d7aa3e",
    "e24ffe67f51f2c6f1a06729543acd8bdf0329dd3419af74ce3f426974c01",
    "16f86b95af98f93150806c1e369c75623fa2d7230b838b8328c420172dd8",
    "303feb50a406a40df70497f995a3d249569020b03c4e5dc997d9235855da",
    "124168d5278addee107a26b22ad1a4b72508fd35982c5d65424e64cf800a",
    "5743d9e10aae1445807b87dfe72da9e43a8a33f99c828cc608667f783e72",
    "1cc736e816b5d1570ef0b2b43686c6ab18671c9f0d7f23a876e5aed97c37",
    "bc25f4e3b1ad6f6cc1d2182ed428db15253eeb96a99666408a3fdb556e50",
    "18ee2897bb1bf631b6042861f18c14baa28c8278e770e93c70e6da8bd765",
    "fe2689caa8d5860b6a182b0a77ffb2ba3d19e8bc00c7d366910f6d16c4c0",
    "1dec19b359675ae7114d33213dc56d42cb6f5aa175a11a06d840754c7cb8",
    "c4372bee0a51a8a2bb7d6de3e23db5b548febcf49756c470d8f1d20c79db",
    "274c29840ae3656ae9a2ac4b56a21186c08b6132ca4f87744d4e672038e0",
    "7e20ebdb9cc1cc05e867e5ae992f1f60faae87f09f848a26eba10aa40005",
    "fe62c23669cfbb5156b94ccad98f612dc8c841488667a2d73e3c89e077b0",
    "da14b0a53c22d9471ef3b51c328e46b6ebe0bb32d84130895ef64607aff3",
    "b2a34380311a11fd1cd88d07fca197ef08901a4ded16db244d84da7850b4",
    "844be29dd6d18ffbc26004eb1a88bea64290d125d010c8e22812f1629712",
    "c63a598f076c55fbf8b0b19177d964cae7a6717040283d5261451b62365c",
    "c46ca70c7dbeae6de91e97526326c1bb173e9fd909db29e9f2e37fd8819e",
    "0fd5adc5d646993ebfd20507f01ea539d639729431364e5ce7dd69cc52a1",
    "91cc8449f236d06490855461fd3ee8fe84dbdb7341911ca2b973ff2151cc",
    "80c633ea10b1e74aa32dad931bc8974b0ba98f615848d288ca81eb3f7eb0",
    "771c0818e4732065f36b2ce91e8387bfb6679d460bd276fc84c1ef1fc41c",
    "1b75ab72dfb553682b84f4928f86c3f6f4aaef0f980f3992c3da44a49e3b",
    "04a97493f9a224c265e4d4eb33eaca44af28fcb92b75e51eab9d0d3f91bb",
    "6ccc206e81aa21626083d49d1768b2b6929f6c097c9d41a5e9b1e75881a7",
    "6da740386d020ee5dd86c9b4c6faf786401f92400913261b77a32dc2d80a",
    "46f66f422949ab7ce0435a80318f86b847c1e4ded61cf527893ccb421d8a",
    "7bcf477b1eb605e40ef2876fdc270dffc8231e4fb33dfe49458a345b5b74",
    "f60df9d22c1d2234b16897c4c67dbbf2f980c43630076598a14cfd9dfd76",
    "6b65d1ffa50c86c23ca4101571d4a9e9221af71274636b161b3c2c129311",
    "7eadbf68f17a41be699aef8651746efefe17fcd92537848d43bd69f70973",
    "87605e9630698f663845382a69b1cb9ca370cc769414a7667f8d55edaddc",
    "ac221449f92051acc8497cdc387d1504e0799261d23ed8073f2fbf400364",
    "97ecccc4b4af6756f93d523b25c3c02d113eb9fc9221f8c38d423ba9d070",
    "78692d30d7ea3a8fd86bb7d79a8df17b1b2756c7b984cefe1c92752f4bfd",
    "78cd0def71f15478f8c74388d8a430a481f4137833110f66a402bbca623f",
    "6963d338a19ea4d42eb3e6c4b99a1a2993881979f8e84304e80931445bb4",
    "276d1805b9aee42431509bc7d496734e306d605af485da027c9249f25a62",
    "80768c352e9522ae97f2b5d5f608ba67a4429010741f6697c6433eb24d1a",
    "1d9f00c012cd5617962e7a32983aa8b5c78915183d2fe3b9d4841aa307dd",
    "1fa8f798afba0ad5d11e9bed24dc3cb40a38a00a7b63ad3f3b8abe8830f1",
    "920d3065c2c9131eb5963d455c0daed1995401f5b3904372f813f9c433c9",
    "53c04bc14c05fc2052be72755274cbcaa8a7a52ed59a0a6601806efc2d83",
    "986aab2df5327fa2b515570a0f867c2234e3d14706c95766b095cccd9f1a",
    "2b8bc42a5b9683d89b71"
  )

  # the reference's own key material: seed[i] = i over 3n bytes, which
  # it splits as SK_SEED || SK_PRF || PUB_SEED
  hx <- function(a, b) paste(sprintf("%02x", a:b), collapse = "")
  key <- pqc_keygen(10L, sk_seed = hx(0, 31), pub_seed = hx(64, 95),
                    sk_prf = hx(32, 63))

  # the root, which is the public key
  expect_identical(
    key$root,
    "9d898033e37af48e6a116f8b15651cc26773467007ad19375d38c23c690c3483")

  sig <- capsule_sign(as.raw(c(1, 2, 3)), key)

  # R = PRF(SK_PRF, toByte(idx, 32))
  expect_identical(
    sig$randomizer,
    "11c3e8f92a6565812dad1b5e748d117a17f1f9f07336cf6c1eaa3a2b77071cb2")

  # and the wire format: idx (4 bytes, big endian) || R || WOTS sig ||
  # auth path, which for this parameter set is 4 + 32 + 2144 + 320
  expect_identical(nchar(sig$wire), 5000L)
  expect_identical(nchar(sig$wire) / 2, 2500)
  expect_identical(sig$wire, ref_sig)

  # the index is big-endian in the first four bytes
  expect_identical(substr(sig$wire, 1L, 8L), "00000000")
  # R follows it
  expect_identical(substr(sig$wire, 9L, 72L), sig$randomizer)
  # then the WOTS signature, 67 chains of 32 bytes
  expect_identical(substr(sig$wire, 73L, 72L + 2L * 67L * 32L),
                   sig$signature)
  # then the authentication path, one node per tree level
  expect_identical(substr(sig$wire, 73L + 2L * 67L * 32L, 5000L),
                   sig$auth)
})

test_that("the conformant signature still verifies, and still refuses", {
  hx <- function(a, b) paste(sprintf("%02x", a:b), collapse = "")
  key <- pqc_keygen(6L, sk_seed = hx(0, 31), pub_seed = hx(64, 95),
                    sk_prf = hx(32, 63))
  msg <- charToRaw("a manifest")
  sig <- capsule_sign(msg, key)
  pub <- signing_public_key(key)
  expect_true(capsule_verify(msg, sig, pub))

  # every tampering still fails -- the conformance work must not have
  # weakened what the scheme actually guarantees
  expect_false(capsule_verify(charToRaw("a manifest."), sig, pub))
  bad <- sig
  bad$randomizer <- paste0("00", substr(sig$randomizer, 3L, 64L))
  expect_false(capsule_verify(msg, bad, pub))
  bad <- sig
  bad$signature <- paste0("00", substr(sig$signature, 3L,
                                       nchar(sig$signature)))
  expect_false(capsule_verify(msg, bad, pub))
  bad <- sig
  bad$auth <- paste0("00", substr(sig$auth, 3L, nchar(sig$auth)))
  expect_false(capsule_verify(msg, bad, pub))
  bad <- sig
  bad$index <- 1L
  expect_false(capsule_verify(msg, bad, pub))
  badpub <- pub
  badpub$root <- paste0("00", substr(pub$root, 3L, 64L))
  expect_false(capsule_verify(msg, sig, badpub))

  # R is part of the signature now, so a signature without one cannot be
  # verified rather than being verified against the wrong digest
  stripped <- sig
  stripped$randomizer <- NULL
  expect_error(capsule_verify(msg, stripped, pub), "no RFC 8391 randomiser")

  # and a key without SK_PRF cannot sign
  oldkey <- key
  oldkey$sk_prf <- NULL
  expect_error(capsule_sign(msg, oldkey), "predates the RFC 8391 randomiser")

  # the randomiser is per-index, so two signatures under one key differ
  s0 <- capsule_sign(msg, key)
  s1 <- capsule_sign(msg, s0$key_state)
  expect_false(identical(s0$randomizer, s1$randomizer))
  expect_true(capsule_verify(msg, s1, pub))
})
