#!/usr/bin/env Rscript
# Generate src/rmbl_barrier.cpp from init.c's CallEntries and rename every
# registered entry point's definition to <name>_impl. Idempotent; run from
# the package root after any change to init.c:
#   Rscript inst/scripts/gen_barrier.R
init <- readLines("src/init.c", warn = FALSE)
m <- regmatches(init, gregexpr('\\{"C_rmbl_[A-Za-z0-9_]+",\\s*\\(DL_FUNC\\) &C_rmbl_[A-Za-z0-9_]+,\\s*[0-9]+\\}', init))
m <- unlist(m)
names_ <- sub('^\\{"(C_rmbl_[A-Za-z0-9_]+)".*$', "\\1", m)
arity <- as.integer(sub("^.*,\\s*([0-9]+)\\}$", "\\1", m))
stopifnot(length(names_) >= 110, !anyDuplicated(names_))

renamed <- 0L
for (f in setdiff(list.files("src", pattern = "[.]cpp$", full.names = TRUE), "src/rmbl_barrier.cpp")) {
  s <- readLines(f, warn = FALSE)
  s2 <- s
  for (n in names_) {
    s2 <- sub(sprintf('^(extern "C" )?SEXP %s\\(', n), sprintf("\\1SEXP %s_impl(", n), s2, perl = TRUE)
  }
  if (!identical(s, s2)) {
    writeLines(s2, f)
    renamed <- renamed + 1L
  }
}
defined <- character(0)
for (f in setdiff(list.files("src", pattern = "[.]cpp$", full.names = TRUE), "src/rmbl_barrier.cpp")) {
  s <- readLines(f, warn = FALSE)
  d <- regmatches(s, regexpr('^(extern "C" )?SEXP C_rmbl_[A-Za-z0-9_]+_impl\\(', s, perl = TRUE))
  defined <- c(defined, sub("_impl\\($", "", sub('^(extern "C" )?SEXP ', "", d, perl = TRUE)))
}
missing <- setdiff(names_, defined)
if (length(missing)) stop("no _impl definition for: ", paste(missing, collapse = ", "))

args_of <- function(a) paste(rep("SEXP", a), collapse = ", ")
params_of <- function(a) if (a == 0) "" else paste(sprintf("SEXP a%d", seq_len(a) - 1L), collapse = ", ")
call_of <- function(a) if (a == 0) "" else paste(sprintf("a%d", seq_len(a) - 1L), collapse = ", ")
out <- c(
  "/* GENERATED by inst/scripts/gen_barrier.R from init.c -- do not edit.",
  " *",
  " * Every registered .Call entry point is a thin wrapper: the implementation",
  " * (<name>_impl, in its own file) runs inside a try block, and any C++",
  " * exception -- std::bad_alloc, a length_error from sizing a vector with an",
  " * NA, anything a kernel throws -- becomes an R error AFTER the block has",
  " * closed, when no C++ object is alive for the longjmp to skip. Without",
  " * this an exception that reaches the extern \"C\" boundary is",
  " * std::terminate(): the R session dies, inside tryCatch() or not. A pending",
  " * interrupt caught the same way is re-raised as R's own interrupt condition.",
  " */",
  "#include <exception>",
  "#include <new>",
  "#include <string>",
  "#include \"rmbl_entry.h\"",
  "",
  "extern \"C\" { int rmbl_kernel_interrupted = 0; }",
  "",
  "/* Raise R's interrupt condition from the API: signal it (so a",
  " * tryCatch(interrupt = ) handler sees it) and unwind to top level, as",
  " * R's own handler does. The pending flag was consumed by the test above,",
  " * so R_CheckUserInterrupt() would not fire again. */",
  "static void rmbl_raise_interrupt(void) {",
  "    R_ParseEvalString(",
  "        \"{ signalCondition(structure(list(message = \\\"interrupt\\\", call = NULL), \"",
  "        \"    class = c(\\\"interrupt\\\", \\\"condition\\\"))); invokeRestart(\\\"abort\\\") }\",",
  "        R_BaseEnv);",
  "}",
  "",
  "/* How many barriers are active on the C stack: 0 means a LinkingTo kernel",
  " * was called by another package's .Call, with no barrier of ours to raise",
  " * the interrupt afterwards. */",
  "static int rmbl_barrier_depth = 0;",
  "",
  "static void rmbl_chk_(void *) { R_CheckUserInterrupt(); }",
  "extern \"C\" int rmbl_interrupt_pending(void) {",
  "    /* R_CheckUserInterrupt() longjmps when one is pending; run it under",
  "     * R_ToplevelExec so the jump is caught here. With a barrier active the",
  "     * kernel stops, sets the flag and the barrier raises after its",
  "     * destructors ran. With none active (a direct LinkingTo call) nobody",
  "     * would raise it: raise it here, which is what R_CheckUserInterrupt()",
  "     * itself would have done, so a Ctrl-C is never swallowed and no",
  "     * caller gets an NA that looks like a result. */",
  "    if (R_ToplevelExec(rmbl_chk_, nullptr)) return 0;",
  "    if (rmbl_barrier_depth == 0) rmbl_raise_interrupt();",
  "    return 1;",
  "}",
  "",
  "template <class F>",
  "static SEXP rmbl_guard(const char *name, F f) {",
  "    std::string msg;",
  "    int kind = 0;",
  "    SEXP r = R_NilValue;",
  "    ++rmbl_barrier_depth;",
  "    rmbl_kernel_interrupted = 0;   /* nothing from an earlier call may leak in */",
  "    try {",
  "        r = f();",
  "        if (rmbl_kernel_interrupted) kind = 1;",
  "    } catch (const rmbl::Interrupt &) {",
  "        kind = 1;",
  "    } catch (const std::bad_alloc &) {",
  "        msg = \"out of memory\";",
  "        kind = 2;",
  "    } catch (const std::exception &e) {",
  "        msg = e.what();",
  "        kind = 2;",
  "    } catch (...) {",
  "        msg = \"unexpected C++ exception\";",
  "        kind = 2;",
  "    }",
  "    /* every path leaves the flag clear and the depth balanced BEFORE the",
  "     * longjmp an error or interrupt makes below */",
  "    rmbl_kernel_interrupted = 0;",
  "    --rmbl_barrier_depth;",
  "    if (kind == 0) return r;",
  "    if (kind == 1) {",
  "        rmbl_raise_interrupt();",
  "        Rf_error(\"%s: interrupted\", name);",
  "    }",
  "    Rf_error(\"%s: %s\", name, msg.c_str());",
  "    return R_NilValue;",
  "}",
  "",
  "extern \"C\" {",
  sprintf("SEXP %s_impl(%s);", names_, vapply(arity, args_of, "")),
  "}",
  "",
  "extern \"C\" {",
  unlist(Map(function(n, a) c(
    sprintf("SEXP %s(%s) {", n, params_of(a)),
    sprintf("    return rmbl_guard(\"%s\", [&] { return %s_impl(%s); });", n, n, call_of(a)),
    "}"), names_, arity)),
  "}"
)
writeLines(out, "src/rmbl_barrier.cpp")
cat(sprintf("barrier: %d entries, renamed definitions in %d file(s)\n", length(names_), renamed))
