"""Generate src/rmbl_barrier.cpp from init.c's CallEntries and rename every
registered entry point's definition to <name>_impl. Idempotent."""
import pathlib, re
src = pathlib.Path("src")
init = (src / "init.c").read_text()
entries = re.findall(r'\{"(C_rmbl_[A-Za-z0-9_]+)",\s*\(DL_FUNC\) &C_rmbl_[A-Za-z0-9_]+,\s*(\d+)\}', init)
assert len(entries) >= 110, len(entries)
names = {n for n, _ in entries}
# rename definitions
renamed = 0
for f in sorted(src.glob("*.cpp")):
    if f.name == "rmbl_barrier.cpp": continue
    s = f.read_text(); orig = s
    for n in names:
        s = re.sub(r'^(extern "C" )?SEXP %s\(' % re.escape(n), lambda m: (m.group(1) or "") + "SEXP %s_impl(" % n, s, flags=re.M)
    if s != orig:
        f.write_text(s); renamed += 1
defined = set()
for f in src.glob("*.cpp"):
    if f.name == "rmbl_barrier.cpp": continue
    defined |= set(re.findall(r'^(?:extern "C" )?SEXP (C_rmbl_[A-Za-z0-9_]+)_impl\(', f.read_text(), flags=re.M))
missing = names - defined
assert not missing, missing
out = ['''/* GENERATED by inst/scripts/gen_barrier.py from init.c -- do not edit.
 *
 * Every registered .Call entry point is a thin wrapper: the implementation
 * (<name>_impl, in its own file) runs inside a try block, and any C++
 * exception -- std::bad_alloc, a length_error from sizing a vector with an
 * NA, anything a kernel throws -- becomes an R error AFTER the block has
 * closed, when no C++ object is alive for the longjmp to skip. Without
 * this an exception that reaches the extern "C" boundary is
 * std::terminate(): the R session dies, inside tryCatch() or not. A pending
 * interrupt caught the same way is re-raised as R's own interrupt.
 */
#include <exception>
#include <new>
#include <string>
#include "rmbl_entry.h"

extern "C" void Rf_onintr(void);
extern "C" int rmbl_kernel_interrupted = 0;

static void rmbl_chk_(void *) { R_CheckUserInterrupt(); }
extern "C" int rmbl_interrupt_pending(void) {
    /* R_CheckUserInterrupt() longjmps when one is pending; run it under
     * R_ToplevelExec so the jump is caught here and reported as FALSE */
    return R_ToplevelExec(rmbl_chk_, nullptr) ? 0 : 1;
}

template <class F>
static SEXP rmbl_guard(const char *name, F f) {
    std::string msg;
    int kind = 0;
    try {
        SEXP r = f();
        if (rmbl_kernel_interrupted) {
            rmbl_kernel_interrupted = 0;
            kind = 1;
        } else {
            return r;
        }
    } catch (const rmbl::Interrupt &) {
        kind = 1;
    } catch (const std::bad_alloc &) {
        msg = "out of memory";
        kind = 2;
    } catch (const std::exception &e) {
        msg = e.what();
        kind = 2;
    } catch (...) {
        msg = "unexpected C++ exception";
        kind = 2;
    }
    if (kind == 1) {
        Rf_onintr();
        Rf_error("%s: interrupted", name);
    }
    Rf_error("%s: %s", name, msg.c_str());
    return R_NilValue;
}

extern "C" {
''']
for n, a in entries:
    a = int(a)
    args = ", ".join("SEXP" for _ in range(a))
    out.append(f"SEXP {n}_impl({args});")
out.append("}\n\nextern \"C\" {\n")
for n, a in entries:
    a = int(a)
    params = ", ".join(f"SEXP a{i}" for i in range(a))
    call = ", ".join(f"a{i}" for i in range(a))
    out.append(f'SEXP {n}({params}) {{\n    return rmbl_guard("{n}", [&] {{ return {n}_impl({call}); }});\n}}')
out.append("}\n")
(src / "rmbl_barrier.cpp").write_text("\n".join(out))
print(f"barrier: {len(entries)} entries, renamed definitions in {renamed} files")
