#!/usr/bin/env bash
# wayback_batch_archive.sh
#
# Rate-limit-safe bulk Wayback Machine submitter.
#
# Wayback's anonymous SavePageNow API allows ~4 saves per minute. This
# script reads a list of URLs (one per line) and submits each with a
# safe 22-second delay, retrying transient failures. Output is a JSON
# inventory mapping each live URL to its snapshot URL — drop the file
# straight into a project's `data_provenance.json` or ship it alongside
# in `wayback_inventory.json`.
#
# USAGE:
#   ./wayback_batch_archive.sh urls.txt                    # default delay 22s
#   ./wayback_batch_archive.sh urls.txt --delay 30         # custom delay
#   ./wayback_batch_archive.sh --from-ckan SLUG            # enumerate via CKAN
#   ./wayback_batch_archive.sh --output inventory.json     # custom out path
#
# REQUIREMENTS:
#   - python3 (used only by this author-side tool, not by shipped bundles)
#   - curl
#
# Licence: AGPL-3.0-or-later.

set -euo pipefail

DELAY=22
OUTPUT="wayback_inventory.json"
FROM_CKAN=""
URLS_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --delay)     DELAY="$2"; shift 2 ;;
    --output)    OUTPUT="$2"; shift 2 ;;
    --from-ckan) FROM_CKAN="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,22p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) URLS_FILE="$1"; shift ;;
  esac
done

if [[ -z "${URLS_FILE}" && -z "${FROM_CKAN}" ]]; then
  echo "ERROR: provide a urls file or --from-ckan SLUG" >&2
  exit 1
fi

# Build URL list
if [[ -n "${FROM_CKAN}" ]]; then
  echo "Enumerating resources from CKAN package '${FROM_CKAN}'..."
  URLS_FILE=$(mktemp)
  python3 -c "
import json, urllib.request, sys
slug = '${FROM_CKAN}'
# Try data.ontario.ca first; can be parameterised later
portal = 'https://data.ontario.ca'
api = f'{portal}/api/3/action/package_show?id={slug}'
d = json.load(urllib.request.urlopen(api, timeout=30))
for r in d['result']['resources']:
    print(r['url'])
# Also archive the catalogue page itself
print(f'{portal}/dataset/{slug}')
print(api)
" > "${URLS_FILE}"
  echo "  Enumerated $(wc -l < "${URLS_FILE}" | tr -d ' ') URLs."
fi

URL_COUNT=$(wc -l < "${URLS_FILE}" | tr -d ' ')
ETA_MIN=$(( URL_COUNT * DELAY / 60 ))

cat <<HDR
==========================================================
Wayback batch archive
==========================================================
URLs:    ${URL_COUNT}
Delay:   ${DELAY} seconds between submissions
ETA:     ~${ETA_MIN} minutes
Output:  ${OUTPUT}
==========================================================

HDR

# Submit each, write JSON inventory
python3 - <<PYEOF
import json, urllib.request, time, sys
urls = [line.strip() for line in open("${URLS_FILE}") if line.strip()]
delay = ${DELAY}
out = {
    "_comment": "Wayback batch submission inventory generated by wayback_batch_archive.sh",
    "tool": "morie-bricklayer wayback_batch_archive.sh",
    "captured_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    "delay_seconds": delay,
    "resources": []
}
for i, url in enumerate(urls, 1):
    print(f'[{i:3d}/{len(urls)}] {url[:80]}', flush=True)
    try:
        req = urllib.request.Request(
            f'https://web.archive.org/save/{url}',
            headers={'User-Agent': 'morie-bricklayer/0.1 wayback_batch_archive.sh'})
        resp = urllib.request.urlopen(req, timeout=180)
        snap = resp.geturl()
        out['resources'].append({
            'live_url': url,
            'snapshot_url': snap,
            'http_code': resp.status
        })
        print(f'           HTTP {resp.status} -> snapshot OK', flush=True)
    except urllib.error.HTTPError as e:
        if e.code == 429:
            print(f'           429 rate-limited. Sleeping 60s and retrying once...', flush=True)
            time.sleep(60)
            try:
                resp = urllib.request.urlopen(req, timeout=180)
                snap = resp.geturl()
                out['resources'].append({'live_url': url, 'snapshot_url': snap, 'http_code': resp.status})
                print(f'           retry HTTP {resp.status} -> snapshot OK', flush=True)
            except Exception as e2:
                out['resources'].append({'live_url': url, 'snapshot_url': None, 'error': f'{type(e2).__name__}: {e2}'})
                print(f'           retry FAILED: {e2}', flush=True)
        else:
            out['resources'].append({'live_url': url, 'snapshot_url': None, 'error': f'HTTP {e.code}'})
            print(f'           FAILED: HTTP {e.code}', flush=True)
    except Exception as e:
        out['resources'].append({'live_url': url, 'snapshot_url': None, 'error': str(e)})
        print(f'           FAILED: {e}', flush=True)
    time.sleep(delay)
json.dump(out, open("${OUTPUT}", "w"), indent=2)
ok = sum(1 for r in out['resources'] if r.get('snapshot_url'))
print(f'\n{ok}/{len(out["resources"])} archived. Wrote ${OUTPUT}')
PYEOF

[[ -n "${FROM_CKAN}" ]] && rm -f "${URLS_FILE}"
