/* GENERATED by inst/scripts/gen_barrier.R from init.c -- do not edit.
 *
 * Every registered .Call entry point is a thin wrapper: the implementation
 * (<name>_impl, in its own file) runs inside a try block, and any C++
 * exception -- std::bad_alloc, a length_error from sizing a vector with an
 * NA, anything a kernel throws -- becomes an R error AFTER the block has
 * closed, when no C++ object is alive for the longjmp to skip. Without
 * this an exception that reaches the extern "C" boundary is
 * std::terminate(): the R session dies, inside tryCatch() or not. A pending
 * interrupt caught the same way is re-raised as R's own interrupt condition.
 */
#include <exception>
#include <new>
#include <string>
#include "rmbl_entry.h"

extern "C" { int rmbl_kernel_interrupted = 0; }

/* Raise R's interrupt condition from the API: signal it (so a
 * tryCatch(interrupt = ) handler sees it) and unwind to top level, as
 * R's own handler does. The pending flag was consumed by the test above,
 * so R_CheckUserInterrupt() would not fire again. */
static void rmbl_raise_interrupt(void) {
    R_ParseEvalString(
        "{ signalCondition(structure(list(message = \"interrupt\", call = NULL), "
        "    class = c(\"interrupt\", \"condition\"))); invokeRestart(\"abort\") }",
        R_BaseEnv);
}

/* How many barriers are active on the C stack: 0 means a LinkingTo kernel
 * was called by another package's .Call, with no barrier of ours to raise
 * the interrupt afterwards. */
static int rmbl_barrier_depth = 0;

static void rmbl_chk_(void *) { R_CheckUserInterrupt(); }
extern "C" int rmbl_interrupt_pending(void) {
    /* R_CheckUserInterrupt() longjmps when one is pending; run it under
     * R_ToplevelExec so the jump is caught here. With a barrier active the
     * kernel stops, sets the flag and the barrier raises after its
     * destructors ran. With none active (a direct LinkingTo call) the
     * kernel returns its sentinel and then calls
     * rmbl_interrupt_raise_unbarriered() with no buffer alive. */
    if (R_ToplevelExec(rmbl_chk_, nullptr)) return 0;
    return 1;
}
/* For an exported kernel called with no barrier on the stack (another
 * package's .Call): raise R's interrupt NOW, from a frame that holds no
 * C++ object. The kernel calls this after its own buffers are gone -- 0.5.8
 * raised from inside rmbl_interrupt_pending(), over live std::vectors
 * (the 0.5.8 diff review). With a barrier active it does nothing: the
 * barrier raises after the entry point returned. */
extern "C" void rmbl_interrupt_raise_unbarriered(void) {
    if (rmbl_barrier_depth == 0) rmbl_raise_interrupt();
}

template <class F>
static SEXP rmbl_guard(const char *name, F f) {
    std::string msg;
    int kind = 0;
    SEXP r = R_NilValue;
    ++rmbl_barrier_depth;
    rmbl_kernel_interrupted = 0;   /* nothing from an earlier call may leak in */
    try {
        r = f();
        if (rmbl_kernel_interrupted) kind = 1;
    } catch (const rmbl::Interrupt &) {
        kind = 1;
    } catch (const std::bad_alloc &) {
        msg = "out of memory";
        kind = 2;
    } catch (const std::exception &e) {
        msg = e.what();
        kind = 2;
    } catch (...) {
        msg = "unexpected C++ exception";
        kind = 2;
    }
    /* every path leaves the flag clear and the depth balanced BEFORE the
     * longjmp an error or interrupt makes below */
    rmbl_kernel_interrupted = 0;
    --rmbl_barrier_depth;
    if (kind == 0) return r;
    if (kind == 1) {
        rmbl_raise_interrupt();
        Rf_error("%s: interrupted", name);
    }
    Rf_error("%s: %s", name, msg.c_str());
    return R_NilValue;
}

extern "C" {
SEXP C_rmbl_mean_impl(SEXP);
SEXP C_rmbl_mean_running_impl(SEXP);
SEXP C_rmbl_var_impl(SEXP);
SEXP C_rmbl_cor_impl(SEXP, SEXP);
SEXP C_rmbl_normal_pdf_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_sha256_impl(SEXP);
SEXP C_rmbl_sha512_impl(SEXP);
SEXP C_rmbl_hash_two_part_impl(SEXP, SEXP);
SEXP C_rmbl_fetch_fallback_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_http_download_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_redirect_check_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_wayback_impl(SEXP, SEXP);
SEXP C_rmbl_url_check_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_siu_html_to_text_impl(SEXP);
SEXP C_rmbl_siu_parse_html_impl(SEXP);
SEXP C_rmbl_siu_to_iso_date_impl(SEXP);
SEXP C_rmbl_siu_resolve_so_impl(SEXP);
SEXP C_rmbl_siu_schema_impl(SEXP);
SEXP C_rmbl_sd_impl(SEXP, SEXP);
SEXP C_rmbl_euclid_impl(SEXP, SEXP);
SEXP C_rmbl_normal_logpdf_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_ipw_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_bootstrap_mean_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_gamma_cdf_impl(SEXP, SEXP);
SEXP C_rmbl_hawkes_nll_grad_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_hawkes_rescaled_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_hawkes_intensity_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_hawkes_em_pass_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_hawkes_cdf_sum_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_uniforms_impl(SEXP, SEXP);
SEXP C_rmbl_hawkes_fit_pbfgs_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_moments_impl(SEXP);
SEXP C_rmbl_quantile_impl(SEXP, SEXP);
SEXP C_rmbl_median_impl(SEXP);
SEXP C_rmbl_mad_impl(SEXP, SEXP);
SEXP C_rmbl_trimmed_mean_impl(SEXP, SEXP);
SEXP C_rmbl_winsorized_mean_impl(SEXP, SEXP);
SEXP C_rmbl_weighted_impl(SEXP, SEXP);
SEXP C_rmbl_cor_spearman_impl(SEXP, SEXP);
SEXP C_rmbl_midranks_impl(SEXP);
SEXP C_rmbl_cov_matrix_impl(SEXP);
SEXP C_rmbl_ks_impl(SEXP, SEXP);
SEXP C_rmbl_psi_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_first_digit_counts_impl(SEXP);
SEXP C_rmbl_crc32_impl(SEXP);
SEXP C_rmbl_gini_impl(SEXP);
SEXP C_rmbl_lorenz_impl(SEXP);
SEXP C_rmbl_top_share_impl(SEXP, SEXP);
SEXP C_rmbl_mann_kendall_impl(SEXP);
SEXP C_rmbl_theil_sen_impl(SEXP, SEXP);
SEXP C_rmbl_sen_slopes_impl(SEXP, SEXP);
SEXP C_rmbl_hurwitz_zeta_impl(SEXP, SEXP);
SEXP C_rmbl_shake_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_prehash_digest_impl(SEXP, SEXP);
SEXP C_rmbl_slhdsa_sign_internal_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_slhdsa_verify_internal_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_mldsa_sizes_impl(SEXP);
SEXP C_rmbl_mldsa_keypair_impl(SEXP, SEXP);
SEXP C_rmbl_mldsa_sign_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_mldsa_mu_impl(SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_mldsa_sign_mu_impl(SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_mldsa_verify_mu_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_mldsa_verify_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_strtod_impl(SEXP);
SEXP C_rmbl_dtoa17_impl(SEXP);
SEXP C_rmbl_sha1_impl(SEXP);
SEXP C_rmbl_sha384_impl(SEXP);
SEXP C_rmbl_hmac_shax_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_mgf1_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_ecdsa_verify_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_ec_mul_impl(SEXP, SEXP);
SEXP C_rmbl_ec_order_impl(SEXP);
SEXP C_rmbl_http_post_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_http_get_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_der_parse_impl(SEXP);
SEXP C_rmbl_rsa_recover_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_mlkem_sizes_impl(SEXP);
SEXP C_rmbl_mlkem_keygen_impl(SEXP, SEXP);
SEXP C_rmbl_mlkem_encaps_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_mlkem_decaps_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_mlkem_decaps_masked_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_hqc_sizes_impl(SEXP);
SEXP C_rmbl_hqc_keygen_impl(SEXP, SEXP);
SEXP C_rmbl_hqc_encaps_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_hqc_decaps_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_hqc_backend_impl(SEXP);
SEXP C_rmbl_hqc_selftest_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_hqc4_sizes_impl(SEXP);
SEXP C_rmbl_hqc4_keygen_impl(SEXP, SEXP);
SEXP C_rmbl_hqc4_encaps_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_hqc4_decaps_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_aes256_encrypt_impl(SEXP, SEXP);
SEXP C_rmbl_drbg_instantiate_impl(SEXP, SEXP);
SEXP C_rmbl_drbg_reseed_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_drbg_generate_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_aes_backend_impl(SEXP);
SEXP C_rmbl_slhdsa_sizes_impl(SEXP);
SEXP C_rmbl_slhdsa_keypair_impl(SEXP, SEXP);
SEXP C_rmbl_slhdsa_sign_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_slhdsa_verify_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_morans_i_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_hmac_sha256_impl(SEXP, SEXP);
SEXP C_rmbl_digest_equal_impl(SEXP, SEXP);
SEXP C_rmbl_merkle_root_impl(SEXP);
SEXP C_rmbl_merkle_leaves_impl(SEXP);
SEXP C_rmbl_merkle_proof_impl(SEXP, SEXP);
SEXP C_rmbl_xmss_keygen_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_xmss_sign_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_xmss_verify_impl(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_pqc_backends_impl();
SEXP C_rmbl_moments_acc_impl(SEXP);
SEXP C_rmbl_moments_merge_impl(SEXP, SEXP);
SEXP C_rmbl_reservoir_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_hll_add_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_hll_count_impl(SEXP);
SEXP C_rmbl_blake2b_impl(SEXP, SEXP, SEXP);
SEXP C_rmbl_pbkdf2_impl(SEXP, SEXP, SEXP, SEXP);
SEXP C_rmbl_os_random_impl(SEXP);
}

extern "C" {
SEXP C_rmbl_mean(SEXP a0) {
    return rmbl_guard("C_rmbl_mean", [&] { return C_rmbl_mean_impl(a0); });
}
SEXP C_rmbl_mean_running(SEXP a0) {
    return rmbl_guard("C_rmbl_mean_running", [&] { return C_rmbl_mean_running_impl(a0); });
}
SEXP C_rmbl_var(SEXP a0) {
    return rmbl_guard("C_rmbl_var", [&] { return C_rmbl_var_impl(a0); });
}
SEXP C_rmbl_cor(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_cor", [&] { return C_rmbl_cor_impl(a0, a1); });
}
SEXP C_rmbl_normal_pdf(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_normal_pdf", [&] { return C_rmbl_normal_pdf_impl(a0, a1, a2); });
}
SEXP C_rmbl_sha256(SEXP a0) {
    return rmbl_guard("C_rmbl_sha256", [&] { return C_rmbl_sha256_impl(a0); });
}
SEXP C_rmbl_sha512(SEXP a0) {
    return rmbl_guard("C_rmbl_sha512", [&] { return C_rmbl_sha512_impl(a0); });
}
SEXP C_rmbl_hash_two_part(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_hash_two_part", [&] { return C_rmbl_hash_two_part_impl(a0, a1); });
}
SEXP C_rmbl_fetch_fallback(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_fetch_fallback", [&] { return C_rmbl_fetch_fallback_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_http_download(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5, SEXP a6) {
    return rmbl_guard("C_rmbl_http_download", [&] { return C_rmbl_http_download_impl(a0, a1, a2, a3, a4, a5, a6); });
}
SEXP C_rmbl_redirect_check(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_redirect_check", [&] { return C_rmbl_redirect_check_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_wayback(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_wayback", [&] { return C_rmbl_wayback_impl(a0, a1); });
}
SEXP C_rmbl_url_check(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_url_check", [&] { return C_rmbl_url_check_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_siu_html_to_text(SEXP a0) {
    return rmbl_guard("C_rmbl_siu_html_to_text", [&] { return C_rmbl_siu_html_to_text_impl(a0); });
}
SEXP C_rmbl_siu_parse_html(SEXP a0) {
    return rmbl_guard("C_rmbl_siu_parse_html", [&] { return C_rmbl_siu_parse_html_impl(a0); });
}
SEXP C_rmbl_siu_to_iso_date(SEXP a0) {
    return rmbl_guard("C_rmbl_siu_to_iso_date", [&] { return C_rmbl_siu_to_iso_date_impl(a0); });
}
SEXP C_rmbl_siu_resolve_so(SEXP a0) {
    return rmbl_guard("C_rmbl_siu_resolve_so", [&] { return C_rmbl_siu_resolve_so_impl(a0); });
}
SEXP C_rmbl_siu_schema(SEXP a0) {
    return rmbl_guard("C_rmbl_siu_schema", [&] { return C_rmbl_siu_schema_impl(a0); });
}
SEXP C_rmbl_sd(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_sd", [&] { return C_rmbl_sd_impl(a0, a1); });
}
SEXP C_rmbl_euclid(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_euclid", [&] { return C_rmbl_euclid_impl(a0, a1); });
}
SEXP C_rmbl_normal_logpdf(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_normal_logpdf", [&] { return C_rmbl_normal_logpdf_impl(a0, a1, a2); });
}
SEXP C_rmbl_ipw(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_ipw", [&] { return C_rmbl_ipw_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_bootstrap_mean(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_bootstrap_mean", [&] { return C_rmbl_bootstrap_mean_impl(a0, a1, a2); });
}
SEXP C_rmbl_gamma_cdf(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_gamma_cdf", [&] { return C_rmbl_gamma_cdf_impl(a0, a1); });
}
SEXP C_rmbl_hawkes_nll_grad(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5, SEXP a6, SEXP a7, SEXP a8, SEXP a9, SEXP a10, SEXP a11) {
    return rmbl_guard("C_rmbl_hawkes_nll_grad", [&] { return C_rmbl_hawkes_nll_grad_impl(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11); });
}
SEXP C_rmbl_hawkes_rescaled(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5, SEXP a6) {
    return rmbl_guard("C_rmbl_hawkes_rescaled", [&] { return C_rmbl_hawkes_rescaled_impl(a0, a1, a2, a3, a4, a5, a6); });
}
SEXP C_rmbl_hawkes_intensity(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5, SEXP a6) {
    return rmbl_guard("C_rmbl_hawkes_intensity", [&] { return C_rmbl_hawkes_intensity_impl(a0, a1, a2, a3, a4, a5, a6); });
}
SEXP C_rmbl_hawkes_em_pass(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5) {
    return rmbl_guard("C_rmbl_hawkes_em_pass", [&] { return C_rmbl_hawkes_em_pass_impl(a0, a1, a2, a3, a4, a5); });
}
SEXP C_rmbl_hawkes_cdf_sum(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_hawkes_cdf_sum", [&] { return C_rmbl_hawkes_cdf_sum_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_uniforms(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_uniforms", [&] { return C_rmbl_uniforms_impl(a0, a1); });
}
SEXP C_rmbl_hawkes_fit_pbfgs(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5, SEXP a6, SEXP a7, SEXP a8, SEXP a9, SEXP a10, SEXP a11, SEXP a12) {
    return rmbl_guard("C_rmbl_hawkes_fit_pbfgs", [&] { return C_rmbl_hawkes_fit_pbfgs_impl(a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12); });
}
SEXP C_rmbl_moments(SEXP a0) {
    return rmbl_guard("C_rmbl_moments", [&] { return C_rmbl_moments_impl(a0); });
}
SEXP C_rmbl_quantile(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_quantile", [&] { return C_rmbl_quantile_impl(a0, a1); });
}
SEXP C_rmbl_median(SEXP a0) {
    return rmbl_guard("C_rmbl_median", [&] { return C_rmbl_median_impl(a0); });
}
SEXP C_rmbl_mad(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_mad", [&] { return C_rmbl_mad_impl(a0, a1); });
}
SEXP C_rmbl_trimmed_mean(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_trimmed_mean", [&] { return C_rmbl_trimmed_mean_impl(a0, a1); });
}
SEXP C_rmbl_winsorized_mean(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_winsorized_mean", [&] { return C_rmbl_winsorized_mean_impl(a0, a1); });
}
SEXP C_rmbl_weighted(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_weighted", [&] { return C_rmbl_weighted_impl(a0, a1); });
}
SEXP C_rmbl_cor_spearman(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_cor_spearman", [&] { return C_rmbl_cor_spearman_impl(a0, a1); });
}
SEXP C_rmbl_midranks(SEXP a0) {
    return rmbl_guard("C_rmbl_midranks", [&] { return C_rmbl_midranks_impl(a0); });
}
SEXP C_rmbl_cov_matrix(SEXP a0) {
    return rmbl_guard("C_rmbl_cov_matrix", [&] { return C_rmbl_cov_matrix_impl(a0); });
}
SEXP C_rmbl_ks(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_ks", [&] { return C_rmbl_ks_impl(a0, a1); });
}
SEXP C_rmbl_psi(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_psi", [&] { return C_rmbl_psi_impl(a0, a1, a2); });
}
SEXP C_rmbl_first_digit_counts(SEXP a0) {
    return rmbl_guard("C_rmbl_first_digit_counts", [&] { return C_rmbl_first_digit_counts_impl(a0); });
}
SEXP C_rmbl_crc32(SEXP a0) {
    return rmbl_guard("C_rmbl_crc32", [&] { return C_rmbl_crc32_impl(a0); });
}
SEXP C_rmbl_gini(SEXP a0) {
    return rmbl_guard("C_rmbl_gini", [&] { return C_rmbl_gini_impl(a0); });
}
SEXP C_rmbl_lorenz(SEXP a0) {
    return rmbl_guard("C_rmbl_lorenz", [&] { return C_rmbl_lorenz_impl(a0); });
}
SEXP C_rmbl_top_share(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_top_share", [&] { return C_rmbl_top_share_impl(a0, a1); });
}
SEXP C_rmbl_mann_kendall(SEXP a0) {
    return rmbl_guard("C_rmbl_mann_kendall", [&] { return C_rmbl_mann_kendall_impl(a0); });
}
SEXP C_rmbl_theil_sen(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_theil_sen", [&] { return C_rmbl_theil_sen_impl(a0, a1); });
}
SEXP C_rmbl_sen_slopes(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_sen_slopes", [&] { return C_rmbl_sen_slopes_impl(a0, a1); });
}
SEXP C_rmbl_hurwitz_zeta(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_hurwitz_zeta", [&] { return C_rmbl_hurwitz_zeta_impl(a0, a1); });
}
SEXP C_rmbl_shake(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_shake", [&] { return C_rmbl_shake_impl(a0, a1, a2); });
}
SEXP C_rmbl_prehash_digest(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_prehash_digest", [&] { return C_rmbl_prehash_digest_impl(a0, a1); });
}
SEXP C_rmbl_slhdsa_sign_internal(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_slhdsa_sign_internal", [&] { return C_rmbl_slhdsa_sign_internal_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_slhdsa_verify_internal(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_slhdsa_verify_internal", [&] { return C_rmbl_slhdsa_verify_internal_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_mldsa_sizes(SEXP a0) {
    return rmbl_guard("C_rmbl_mldsa_sizes", [&] { return C_rmbl_mldsa_sizes_impl(a0); });
}
SEXP C_rmbl_mldsa_keypair(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_mldsa_keypair", [&] { return C_rmbl_mldsa_keypair_impl(a0, a1); });
}
SEXP C_rmbl_mldsa_sign(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5, SEXP a6) {
    return rmbl_guard("C_rmbl_mldsa_sign", [&] { return C_rmbl_mldsa_sign_impl(a0, a1, a2, a3, a4, a5, a6); });
}
SEXP C_rmbl_mldsa_mu(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4) {
    return rmbl_guard("C_rmbl_mldsa_mu", [&] { return C_rmbl_mldsa_mu_impl(a0, a1, a2, a3, a4); });
}
SEXP C_rmbl_mldsa_sign_mu(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4) {
    return rmbl_guard("C_rmbl_mldsa_sign_mu", [&] { return C_rmbl_mldsa_sign_mu_impl(a0, a1, a2, a3, a4); });
}
SEXP C_rmbl_mldsa_verify_mu(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_mldsa_verify_mu", [&] { return C_rmbl_mldsa_verify_mu_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_mldsa_verify(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5) {
    return rmbl_guard("C_rmbl_mldsa_verify", [&] { return C_rmbl_mldsa_verify_impl(a0, a1, a2, a3, a4, a5); });
}
SEXP C_rmbl_strtod(SEXP a0) {
    return rmbl_guard("C_rmbl_strtod", [&] { return C_rmbl_strtod_impl(a0); });
}
SEXP C_rmbl_dtoa17(SEXP a0) {
    return rmbl_guard("C_rmbl_dtoa17", [&] { return C_rmbl_dtoa17_impl(a0); });
}
SEXP C_rmbl_sha1(SEXP a0) {
    return rmbl_guard("C_rmbl_sha1", [&] { return C_rmbl_sha1_impl(a0); });
}
SEXP C_rmbl_sha384(SEXP a0) {
    return rmbl_guard("C_rmbl_sha384", [&] { return C_rmbl_sha384_impl(a0); });
}
SEXP C_rmbl_hmac_shax(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_hmac_shax", [&] { return C_rmbl_hmac_shax_impl(a0, a1, a2); });
}
SEXP C_rmbl_mgf1(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_mgf1", [&] { return C_rmbl_mgf1_impl(a0, a1, a2); });
}
SEXP C_rmbl_ecdsa_verify(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5) {
    return rmbl_guard("C_rmbl_ecdsa_verify", [&] { return C_rmbl_ecdsa_verify_impl(a0, a1, a2, a3, a4, a5); });
}
SEXP C_rmbl_ec_mul(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_ec_mul", [&] { return C_rmbl_ec_mul_impl(a0, a1); });
}
SEXP C_rmbl_ec_order(SEXP a0) {
    return rmbl_guard("C_rmbl_ec_order", [&] { return C_rmbl_ec_order_impl(a0); });
}
SEXP C_rmbl_http_post(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5) {
    return rmbl_guard("C_rmbl_http_post", [&] { return C_rmbl_http_post_impl(a0, a1, a2, a3, a4, a5); });
}
SEXP C_rmbl_http_get(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_http_get", [&] { return C_rmbl_http_get_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_der_parse(SEXP a0) {
    return rmbl_guard("C_rmbl_der_parse", [&] { return C_rmbl_der_parse_impl(a0); });
}
SEXP C_rmbl_rsa_recover(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_rsa_recover", [&] { return C_rmbl_rsa_recover_impl(a0, a1, a2); });
}
SEXP C_rmbl_mlkem_sizes(SEXP a0) {
    return rmbl_guard("C_rmbl_mlkem_sizes", [&] { return C_rmbl_mlkem_sizes_impl(a0); });
}
SEXP C_rmbl_mlkem_keygen(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_mlkem_keygen", [&] { return C_rmbl_mlkem_keygen_impl(a0, a1); });
}
SEXP C_rmbl_mlkem_encaps(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_mlkem_encaps", [&] { return C_rmbl_mlkem_encaps_impl(a0, a1, a2); });
}
SEXP C_rmbl_mlkem_decaps(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_mlkem_decaps", [&] { return C_rmbl_mlkem_decaps_impl(a0, a1, a2); });
}
SEXP C_rmbl_mlkem_decaps_masked(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_mlkem_decaps_masked", [&] { return C_rmbl_mlkem_decaps_masked_impl(a0, a1, a2); });
}
SEXP C_rmbl_hqc_sizes(SEXP a0) {
    return rmbl_guard("C_rmbl_hqc_sizes", [&] { return C_rmbl_hqc_sizes_impl(a0); });
}
SEXP C_rmbl_hqc_keygen(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_hqc_keygen", [&] { return C_rmbl_hqc_keygen_impl(a0, a1); });
}
SEXP C_rmbl_hqc_encaps(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_hqc_encaps", [&] { return C_rmbl_hqc_encaps_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_hqc_decaps(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_hqc_decaps", [&] { return C_rmbl_hqc_decaps_impl(a0, a1, a2); });
}
SEXP C_rmbl_hqc_backend(SEXP a0) {
    return rmbl_guard("C_rmbl_hqc_backend", [&] { return C_rmbl_hqc_backend_impl(a0); });
}
SEXP C_rmbl_hqc_selftest(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_hqc_selftest", [&] { return C_rmbl_hqc_selftest_impl(a0, a1, a2); });
}
SEXP C_rmbl_hqc4_sizes(SEXP a0) {
    return rmbl_guard("C_rmbl_hqc4_sizes", [&] { return C_rmbl_hqc4_sizes_impl(a0); });
}
SEXP C_rmbl_hqc4_keygen(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_hqc4_keygen", [&] { return C_rmbl_hqc4_keygen_impl(a0, a1); });
}
SEXP C_rmbl_hqc4_encaps(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_hqc4_encaps", [&] { return C_rmbl_hqc4_encaps_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_hqc4_decaps(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_hqc4_decaps", [&] { return C_rmbl_hqc4_decaps_impl(a0, a1, a2); });
}
SEXP C_rmbl_aes256_encrypt(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_aes256_encrypt", [&] { return C_rmbl_aes256_encrypt_impl(a0, a1); });
}
SEXP C_rmbl_drbg_instantiate(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_drbg_instantiate", [&] { return C_rmbl_drbg_instantiate_impl(a0, a1); });
}
SEXP C_rmbl_drbg_reseed(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_drbg_reseed", [&] { return C_rmbl_drbg_reseed_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_drbg_generate(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_drbg_generate", [&] { return C_rmbl_drbg_generate_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_aes_backend(SEXP a0) {
    return rmbl_guard("C_rmbl_aes_backend", [&] { return C_rmbl_aes_backend_impl(a0); });
}
SEXP C_rmbl_slhdsa_sizes(SEXP a0) {
    return rmbl_guard("C_rmbl_slhdsa_sizes", [&] { return C_rmbl_slhdsa_sizes_impl(a0); });
}
SEXP C_rmbl_slhdsa_keypair(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_slhdsa_keypair", [&] { return C_rmbl_slhdsa_keypair_impl(a0, a1); });
}
SEXP C_rmbl_slhdsa_sign(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5) {
    return rmbl_guard("C_rmbl_slhdsa_sign", [&] { return C_rmbl_slhdsa_sign_impl(a0, a1, a2, a3, a4, a5); });
}
SEXP C_rmbl_slhdsa_verify(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5) {
    return rmbl_guard("C_rmbl_slhdsa_verify", [&] { return C_rmbl_slhdsa_verify_impl(a0, a1, a2, a3, a4, a5); });
}
SEXP C_rmbl_morans_i(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5, SEXP a6) {
    return rmbl_guard("C_rmbl_morans_i", [&] { return C_rmbl_morans_i_impl(a0, a1, a2, a3, a4, a5, a6); });
}
SEXP C_rmbl_hmac_sha256(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_hmac_sha256", [&] { return C_rmbl_hmac_sha256_impl(a0, a1); });
}
SEXP C_rmbl_digest_equal(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_digest_equal", [&] { return C_rmbl_digest_equal_impl(a0, a1); });
}
SEXP C_rmbl_merkle_root(SEXP a0) {
    return rmbl_guard("C_rmbl_merkle_root", [&] { return C_rmbl_merkle_root_impl(a0); });
}
SEXP C_rmbl_merkle_leaves(SEXP a0) {
    return rmbl_guard("C_rmbl_merkle_leaves", [&] { return C_rmbl_merkle_leaves_impl(a0); });
}
SEXP C_rmbl_merkle_proof(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_merkle_proof", [&] { return C_rmbl_merkle_proof_impl(a0, a1); });
}
SEXP C_rmbl_xmss_keygen(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_xmss_keygen", [&] { return C_rmbl_xmss_keygen_impl(a0, a1, a2); });
}
SEXP C_rmbl_xmss_sign(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5) {
    return rmbl_guard("C_rmbl_xmss_sign", [&] { return C_rmbl_xmss_sign_impl(a0, a1, a2, a3, a4, a5); });
}
SEXP C_rmbl_xmss_verify(SEXP a0, SEXP a1, SEXP a2, SEXP a3, SEXP a4, SEXP a5, SEXP a6, SEXP a7) {
    return rmbl_guard("C_rmbl_xmss_verify", [&] { return C_rmbl_xmss_verify_impl(a0, a1, a2, a3, a4, a5, a6, a7); });
}
SEXP C_rmbl_pqc_backends() {
    return rmbl_guard("C_rmbl_pqc_backends", [&] { return C_rmbl_pqc_backends_impl(); });
}
SEXP C_rmbl_moments_acc(SEXP a0) {
    return rmbl_guard("C_rmbl_moments_acc", [&] { return C_rmbl_moments_acc_impl(a0); });
}
SEXP C_rmbl_moments_merge(SEXP a0, SEXP a1) {
    return rmbl_guard("C_rmbl_moments_merge", [&] { return C_rmbl_moments_merge_impl(a0, a1); });
}
SEXP C_rmbl_reservoir(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_reservoir", [&] { return C_rmbl_reservoir_impl(a0, a1, a2); });
}
SEXP C_rmbl_hll_add(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_hll_add", [&] { return C_rmbl_hll_add_impl(a0, a1, a2); });
}
SEXP C_rmbl_hll_count(SEXP a0) {
    return rmbl_guard("C_rmbl_hll_count", [&] { return C_rmbl_hll_count_impl(a0); });
}
SEXP C_rmbl_blake2b(SEXP a0, SEXP a1, SEXP a2) {
    return rmbl_guard("C_rmbl_blake2b", [&] { return C_rmbl_blake2b_impl(a0, a1, a2); });
}
SEXP C_rmbl_pbkdf2(SEXP a0, SEXP a1, SEXP a2, SEXP a3) {
    return rmbl_guard("C_rmbl_pbkdf2", [&] { return C_rmbl_pbkdf2_impl(a0, a1, a2, a3); });
}
SEXP C_rmbl_os_random(SEXP a0) {
    return rmbl_guard("C_rmbl_os_random", [&] { return C_rmbl_os_random_impl(a0); });
}
}
